[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "trexdiff"
version = "0.1.0"
requires-python = ">=3.10"

[tool.setuptools.packages.find]
where = ["python"]
include = ["trexdiff*"]

[tool.setuptools.package-dir]
"" = "python"

[tool.setuptools.package-data]
trexdiff = ["libtrexdiff.so"]
